STORAGE_FOLDER_PATH = 'D:\Work\Personal\Projects\Stock Analyser\Storage\\'
INDICES_FOLDER_PATH = STORAGE_FOLDER_PATH + 'Indices\\'
OHLCV_DATA_FOLDER = STORAGE_FOLDER_PATH + 'OHLCV Data\\'
BACKTEST_DATA_FOLDER = STORAGE_FOLDER_PATH + 'Backtest Results\\'